### ISSUE TITLE
Repeated rarefaction: rarefied matrices not really random?

### ISSUE THREAD

**Issue by marcelglueck** [hildebra/Rarefaction#30]
Dear all, 

I would like to use this package for my analyses. My aim is to rarefy a large composite (lets say 100 000 columns and 300 rows) repeatedly (300 times) on a consumer notebook with 16 GB of memory. As the rarefied matrices are held in memory, not all requested rarefactions can be performed at once. Instead, I break the number of repeats in chunks of ten and combine them later.

Pursuing this approach, I realized that within runs, the different rarefied matrices are not completely random but resemble each other more closely than matrices constructed with different seeds.

To reproduce this, take the following code:

```R
library(rtk)

data <- matrix(sample(x = c(rep(0, 1500),rep(1:10, 500),1:1000),
                      size = 1500000, replace = TRUE), 150)

min_sample <- min(rowSums(data)[rowSums(data) > 0])
seeds <- c(1:10)
res_list <- list()

for (i in 1:10) {
  seed <- seeds[i]
  res_rtk <-
    rtk(
      input = data,
      repeats = 10,
      depth = min_sample,
      ReturnMatrix = 10,
      margin = 1,
      verbose = FALSE,
      threads = 3,
      seed = seed
    )
  res_list <- c(res_list, list(res_rtk[["raremat"]]))
}
```

Comparing list 1 and 2 of res_list, one can clearly see that within lists, sub-lists are very similar to one another while the main differences is between seeds/lists. Hence, one could say that the number of repeated rarefaction is not 100 (number of iterations * number of repeats), but simply the number of independent iterations (10). 

Is there a way to circumvent this? Of course, I could perform separate rarefaction runs with both repeates and ReturnMatrix set to one, but the overhead might easily negate the benefits of multi-core support. Perfect would be the ability to parse a vector of length repeats/ReturnMatrix containing seed values to 'seed', but so far, this does not seem possible?

Thanks for your help.

**Comment by hildebra** [comment]
Hey Marcel,
are the 10 matrices from the repeats exactly the same? Or the 10 matrices within each of the 10 repeats always the same 10 matrices?

best, Falk

**Comment by marcelglueck** [comment]
Hi Frank,

thanks for the fast reply. I am not sure whether I understood you fully. I am not speaking of fully identical results but of high similarity of the rarefied matrices constructed by repeats/ReturnMatrix.

To clarify, the 10 matrices constructed by repeats/ReturnMatrix =10 are very similar. This is surprising to me, because they should represent independent rarefactions and hence, I expected them to be far more variable.  But, obviously, the main variance is not across same-seed repeats but across different seed values/iterations of my loop. The following image exemplifies this: The location of high and low values is shaped by seed valus and does not vary across the 10 matrices constructed by repeats = 10.

 ![rtk_issue](https://github.com/hildebra/Rarefaction/assets/71122201/a369a3e2-764e-4fc4-80b6-1f66b710abf2)

I realized that I did not make my example reproducible. Here is the correct code:

```R
library(rtk)
set.seed(45755782)
data <- matrix(sample(x = c(rep(0, 1500),rep(1:10, 500),1:1000),
                      size = 1500000, replace = TRUE), 150)
min_sample <- min(rowSums(data)[rowSums(data) > 0])
seeds <- c(1:10)
res_list <- list()

for (i in 1:10) {
  seed <- seeds[i]
  res_rtk <-
    rtk(
      input = data,
      repeats = 10,
      depth = min_sample,
      ReturnMatrix = 10,
      margin = 1,
      verbose = FALSE,
      threads = 3,
      seed = seed
    )
  res_list <- c(res_list, list(res_rtk[["raremat"]]))
}
```

**Comment by marcelglueck** [comment]
Interestingly, it seems that rtk's operation cannot be made fully reproducible. I ran the code above anew and it produced different results. Hence, you might have to run it several times to find the pattern shown in the image.

**Comment by hildebra** [comment]
ahh I think I know what this is: please be advised that currently the columns will be resorted by rtk, and this is sadly a bit random. The interface return a column name though, and this should be used to "resort" again into the original column order.
We have a patch for this, but currrently don't have the bandwidth to update the R package. @apduncan  is the updated R code by any chance in the repository already? @openpaul  might be good to upload this to R if you find the time, this is a recurring problem.

Marcel, hope this is really the problem?

**Comment by marcelglueck** [comment]
Thanks. Since margin = 1, samples are rows. After making row numbers to names, the re-sorting by rtk becomes apparent and can be corrected. This was fast, thank you guys! :)

**Comment by apduncan** [comment]
>  @apduncan is the updated R code by any chance in the repository already? @openpaul might be good to upload this to R if you find the time, this is a recurring problem.

Yep, this was merged in in https://github.com/hildebra/Rarefaction/commit/79c3f728ebe0c5ab99caf51c7b1148c33eaf2094
